---
inputs:
  php-version:
    required: true
runs:
  using: composite
  steps:
    - id: phpunit_version
      if: inputs.php-version == '7.2'
      shell: bash
      run: echo phpunit_version=:8.5 >>"$GITHUB_OUTPUT"

    - uses: actions/checkout@v3

    - uses: shivammathur/setup-php@e04e1d97f0c0481c6e1ba40f8a538454fe5d7709 # 2.21.2
      with:
        php-version: ${{ inputs.php-version }}
        tools: phpunit${{ steps.phpunit_version.outputs.phpunit_version }}

    - shell: bash
      run: exec sudo '${{ github.action_path }}/action.bash'
