---
inputs:
  php-version:
    required: true
  extensions: {}
runs:
  using: composite
  steps:
    - id: phpunit_version
      if: inputs.php-version == '7.2'
      shell: bash
      run: echo phpunit_version=:8.5 >>"$GITHUB_OUTPUT"

    - uses: actions/checkout@v3

    - uses: shivammathur/setup-php@e04e1d97f0c0481c6e1ba40f8a538454fe5d7709 # 2.21.2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.extensions }}
        ini-values: include_path=.:/usr/share/php:/usr/share/icingaweb2/library:/usr/share/icingaweb2/library/vendor
        tools: phpunit${{ steps.phpunit_version.outputs.phpunit_version }}

    - shell: bash
      run: |
        sudo '${{ github.action_path }}/action.bash'
        icingacli test php unit --include "Tests\\Icinga\\Modules\\X509" --verbose
