---
inputs:
  php-version:
    required: true
runs:
  using: composite
  steps:
    - uses: shivammathur/setup-php@e04e1d97f0c0481c6e1ba40f8a538454fe5d7709 # 2.21.2
      with:
        php-version: ${{ inputs.php-version }}
    - shell: bash
      run: exec php -v
